apiVersion: v1
kind: ReplicationController
metadata:
  name: gameoflifejava-rc
spec:
   replicas: 3
   selector: 
     app: gameoflifejava
     version: 2.6.2
   template:
     metadata:
       labels:
          app: gameoflifejava
          version: 2.6.2
     spec:
        containers:
        - name: gameoflifejava-container
          image: nbktechnosys/mygameoflife16aug22:1
          ports:
          - containerPort: 8080 