apiVersion: v1
kind: ReplicationController
metadata:
  name: mymahajava-rc
spec:
   replicas: 3
   selector: 
     app: mymahajava
     version: 2.6.2
   template:
     metadata:
       labels:
          app: mymahajava
          version: 2.6.2
     spec:
        containers:
        - name: mymahajava-container
          image: maha4ntvc/ mahalogin:2
          ports:
          - containerPort: 8080 